CREATE TABLE USUARIO(
ID SERIAL PRIMARY KEY,
LOGIN VARCHAR(50) NOT NULL,
SENHA VARCHAR(32) NOT NULL,
ADMIN BOOLEAN NOT NULL
);

CREATE TABLE LOCALIDADE(
ID SERIAL PRIMARY KEY,
CIDADE VARCHAR(50) NOT NULL,
ENDERECO VARCHAR(80),
PAIS VARCHAR(30) NOT NULL,
OUTROS VARCHAR(70)
);

CREATE TABLE ESCOLARIDADE(
ID SERIAL PRIMARY KEY,
GRAU VARCHAR(40) NOT NULL
);

CREATE TABLE FAMILIA(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(30) NOT NULL,
MEMBROS INTEGER
);

CREATE TABLE PESSOA(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(70) NOT NULL,
DATA_NASC DATE,
DATA_OBITO DATE,
LOCAL_NASC INTEGER,
LOCAL_OBITO INTEGER,
PROFISSAO VARCHAR(50),
ESCOLARIDADE INTEGER,
TITULOS VARCHAR(256),
HISTORIA TEXT,
ORIGEM TEXT,
FOTO INTEGER,

FAMILIA INTEGER,
PAI INTEGER,
MAE INTEGER,
IRMAO INTEGER,

FOREIGN KEY (FAMILIA) REFERENCES FAMILIA,
FOREIGN KEY (PAI) REFERENCES PESSOA,
FOREIGN KEY (MAE) REFERENCES PESSOA,
FOREIGN KEY (IRMAO) REFERENCES PESSOA,

FOREIGN KEY (LOCAL_NASC) REFERENCES LOCALIDADE,
FOREIGN KEY (LOCAL_OBITO) REFERENCES LOCALIDADE,
FOREIGN KEY (ESCOLARIDADE) REFERENCES ESCOLARIDADE,
FOREIGN KEY (FOTO) REFERENCES FOTO
);

CREATE TABLE FOTO(
ID BIGSERIAL PRIMARY KEY,
URL VARCHAR(100) NOT NULL
);

CREATE TABLE PESSOA_TEMP(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(70) NOT NULL,
DATA_NASC DATE,
DATA_OBITO DATE,
LOCAL_NASC INTEGER,
LOCAL_OBITO INTEGER,
PROFISSAO VARCHAR(50),
ESCOLARIDADE INTEGER,
TITULOS VARCHAR(256),
HISTORIA TEXT,
ORIGEM TEXT,
FOTO INTEGER,

PAI INTEGER,
MAE INTEGER,

FOREIGN KEY (PAI) REFERENCES PESSOA,
FOREIGN KEY (MAE) REFERENCES PESSOA,

FOREIGN KEY (LOCAL_NASC) REFERENCES LOCALIDADE,
FOREIGN KEY (LOCAL_OBITO) REFERENCES LOCALIDADE,
FOREIGN KEY (ESCOLARIDADE) REFERENCES ESCOLARIDADE,
FOREIGN KEY (FOTO) REFERENCES FOTO
);