CREATE TABLE USUARIO(
ID SERIAL PRIMARY KEY,
LOGIN VARCHAR(50) NOT NULL,
SENHA VARCHAR(32) NOT NULL,
ADMIN BOOLEAN NOT NULL
);

CREATE TABLE LOCALIDADE(
ID SERIAL PRIMARY KEY,
CIDADE VARCHAR(50) NOT NULL,
ENDERECO VARCHAR(80),
PAIS VARCHAR(30) NOT NULL,
OUTROS VARCHAR(70)
);

CREATE TABLE ESCOLARIDADE(
ID SERIAL PRIMARY KEY,
GRAU VARCHAR(40) NOT NULL
);

CREATE TABLE PESSOA(
ID SERIAL PRIMARY KEY,
NOME VARCHAR (70) NOT NULL,
DATA_NASC DATE,
DATA_OBITO DATE,
LOCAL_NASC INTEGER,
LOCAL_OBITO INTEGER,
PROFISSAO VARCHAR(50),
ESCOLARIDADE INTEGER,
TITULOS VARCHAR(256),
HISTORIA TEXT,
ORIGEM TEXT,

PAI INTEGER,
MAE INTEGER,
IRMAO INTEGER,
IRMA INTEGER,
FILHO INTEGER,
FILHA INTEGER,

FOREIGN KEY (PAI) REFERENCES PESSOA,
FOREIGN KEY (MAE) REFERENCES PESSOA,
FOREIGN KEY (IRMAO) REFERENCES PESSOA,
FOREIGN KEY (IRMA) REFERENCES PESSOA,
FOREIGN KEY (FILHO) REFERENCES PESSOA,
FOREIGN KEY (FILHA) REFERENCES PESSOA,

FOREIGN KEY (LOCAL_NASC) REFERENCES LOCALIDADE,
FOREIGN KEY (LOCAL_OBITO) REFERENCES LOCALIDADE,
FOREIGN KEY (ESCOLARIDADE) REFERENCES ESCOLARIDADE
);

CREATE TABLE FOTO(
ID BIGSERIAL PRIMARY KEY,
URL VARCHAR(100) NOT NULL
);

CREATE TABLE GALERIA(
FOTO BIGINT NOT NULL,
PESSOA INTEGER NOT NULL,

PRIMARY KEY (FOTO, PESSOA)
);